name: Unit test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-and-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Node
        uses: actions/setup-node@v4
  test:
    needs: install-and-setup

    steps:
     - name: Test
     - run: npm ci
     - run: npm run test:all