name: Unit test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-and-setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Node
        uses: actions/setup-node@v3
  test:
    runs-on: ubuntu-latest
    needs: install-and-setup

    steps:
     - run: npm ci
     - run: npm run test:all
  build:
    needs: install-and-setup
    runs-on: ubuntu-latest

    steps:
     - run: npm ci
     - run: npm run build